name= ESP32 Cytron Drivers Library
version=1.0
author=Saksham
maintainer=
sentence=Library for ESP32 to control Cytron Motor Drivers.
paragraph=Provide examples on how to use the motor drivers.
category=Device Control
url=
architectures=*